### ISSUE TITLE
More standardized naming on endpoints

### ISSUE THREAD

**Issue by rafatrigo** [Deshan555/diaryAPI#2]
Hi, I would like to suggest a modification to the endpoints.

There is nothing wrong with endpoints the way they are now. However, it would be better for your project if it used a more common design. Endpoints following a more well-known standard would make it easier for people to use and contribute to your project.

Here are some good practices:

- Easy to read and work with.
- Resources with plural names (not mandatory, but most APIs use it that way)
- Do not use verbs in the URL

The GET, PUT, POST and DELETE operations are already used to say what you want to do in the resource described by the URL.
If you want to add a daybook you don't need to do ```POST /api/v1/daybook/add```

Because if you are using the ```POST``` method you are already informing that you want to **add** something. So you can just use ```POST /api/v1/daybooks/``` this already tells you that you want to add a daybook

Following the practices above:

- **Add a new daybook entry**.
```POST /api/v1/daybooks/```

- **Update an existing daybook entry.**
```PUT /api/v1/daybooks/{id}``` - id is the id of the daybook you want to update

- **Retrieve a specific daybook entry by its ID.**
```GET /api/v1/daybooks/{id}```

- **Retrieve a list of all daybook entries.**
```GET /api/v1/daybooks/```

- **Delete a daybook entry by its ID.**
```DELETE /api/v1/daybooks/{id}```

I hope I've helped ;)

You can read more about the topic here: https://swagger.io/resources/articles/best-practices-in-api-design/

**Comment by Deshan555** [comment]
Thanks For Your suggestions and advices about my works, i will follow your suggestions my future projects
